/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Modelo.Arquivo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wagner
 */
public class Principal extends javax.swing.JFrame {
       
    int numSenha = 1;
    private ArrayList<String> SenhasChamadas = new ArrayList<>();
    private ArrayList<String> RegistroSenhas = new ArrayList<>();
    String regSenha;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setResizable(false);
        TelaPainel novatela = new TelaPainel();
        Login novaJanelaLogin = new Login();
    }
    
    
    private void limparTabela() {
        while (jTableSenhas.getRowCount() > 0) {
        DefaultTableModel tabela = (DefaultTableModel) jTableSenhas.getModel();
        tabela.getDataVector().removeAllElements();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHora = new javax.swing.JPanel();
        jLabelHora = new javax.swing.JLabel();
        jLabeData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelSuperior = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonConfig = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSenhas = new javax.swing.JTable();
        jPanelSenhas = new javax.swing.JPanel();
        jLabelSenhaAtual = new javax.swing.JLabel();
        jLabelSenhaAnt = new javax.swing.JLabel();
        jLabelSenhaAnt2 = new javax.swing.JLabel();
        jLabelSenhaAnt3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonChamarSenha = new javax.swing.JButton();
        jButtonApagarSenha = new javax.swing.JButton();
        jButtonRechamarSenha = new javax.swing.JButton();
        jButtonAbrirPainel = new javax.swing.JButton();
        jButtonNovaSenha = new javax.swing.JButton();
        jLabelNovaSenha = new javax.swing.JLabel();
        jLabelChamarSenha = new javax.swing.JLabel();
        jLabelRechamarSenha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("iPainel");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelHora.setBackground(new java.awt.Color(36, 40, 65));
        jPanelHora.setPreferredSize(new java.awt.Dimension(842, 40));

        jLabelHora.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHora.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabeData.setBackground(new java.awt.Color(255, 255, 255));
        jLabeData.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabeData.setForeground(new java.awt.Color(255, 255, 255));
        jLabeData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("₢ Todos os seus direitos reservados");

        javax.swing.GroupLayout jPanelHoraLayout = new javax.swing.GroupLayout(jPanelHora);
        jPanelHora.setLayout(jPanelHoraLayout);
        jPanelHoraLayout.setHorizontalGroup(
            jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHoraLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(306, 306, 306)
                .addComponent(jLabeData, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanelHoraLayout.setVerticalGroup(
            jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHoraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabeData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
        );

        jPanelSuperior.setBackground(new java.awt.Color(36, 40, 65));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("iPanel");

        jButtonConfig.setBackground(new java.awt.Color(30, 51, 80));
        jButtonConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/config.png"))); // NOI18N
        jButtonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(30, 51, 80));
        jButtonSair.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/exit.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelPrincipal.setBackground(new java.awt.Color(36, 45, 67));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(827, 579));

        jTableSenhas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableSenhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Senhas"
            }
        ));
        jScrollPane1.setViewportView(jTableSenhas);

        jPanelSenhas.setBackground(new java.awt.Color(36, 45, 67));
        jPanelSenhas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha Atual", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabelSenhaAtual.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabelSenhaAtual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelSenhaAnt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSenhaAnt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaAnt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelSenhaAnt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSenhaAnt2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaAnt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelSenhaAnt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSenhaAnt3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaAnt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Senhas Chamadas");

        javax.swing.GroupLayout jPanelSenhasLayout = new javax.swing.GroupLayout(jPanelSenhas);
        jPanelSenhas.setLayout(jPanelSenhasLayout);
        jPanelSenhasLayout.setHorizontalGroup(
            jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSenhasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSenhasLayout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSenhasLayout.createSequentialGroup()
                                .addComponent(jLabelSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSenhasLayout.createSequentialGroup()
                                .addComponent(jLabelSenhaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabelSenhaAnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabelSenhaAnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelSenhasLayout.setVerticalGroup(
            jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSenhasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelSenhaAnt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabelSenhaAnt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSenhaAnt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        jButtonChamarSenha.setBackground(new java.awt.Color(30, 51, 80));
        jButtonChamarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/chamar.png"))); // NOI18N
        jButtonChamarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChamarSenhaActionPerformed(evt);
            }
        });
        jButtonChamarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonChamarSenhaKeyPressed(evt);
            }
        });

        jButtonApagarSenha.setBackground(new java.awt.Color(30, 51, 80));
        jButtonApagarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/apagar.png"))); // NOI18N
        jButtonApagarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarSenhaActionPerformed(evt);
            }
        });

        jButtonRechamarSenha.setBackground(new java.awt.Color(30, 51, 80));
        jButtonRechamarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/rechama.png"))); // NOI18N
        jButtonRechamarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechamarSenhaActionPerformed(evt);
            }
        });
        jButtonRechamarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonRechamarSenhaKeyPressed(evt);
            }
        });

        jButtonAbrirPainel.setBackground(new java.awt.Color(30, 51, 80));
        jButtonAbrirPainel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonAbrirPainel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAbrirPainel.setText("Iniciar Painel Cliente");
        jButtonAbrirPainel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPainelActionPerformed(evt);
            }
        });

        jButtonNovaSenha.setBackground(new java.awt.Color(30, 51, 80));
        jButtonNovaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/add.png"))); // NOI18N
        jButtonNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaSenhaActionPerformed(evt);
            }
        });
        jButtonNovaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonNovaSenhaKeyPressed(evt);
            }
        });

        jLabelNovaSenha.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabelNovaSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNovaSenha.setText("Nova");

        jLabelChamarSenha.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabelChamarSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChamarSenha.setText("Chamar");

        jLabelRechamarSenha.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabelRechamarSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRechamarSenha.setText("Rechamar");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Excluir Senha");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jButtonNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChamarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelNovaSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelChamarSenha)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRechamarSenha)
                            .addComponent(jButtonRechamarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButtonApagarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanelSenhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jButtonAbrirPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNovaSenha)
                            .addComponent(jLabelChamarSenha)
                            .addComponent(jLabelRechamarSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRechamarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonChamarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonApagarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButtonAbrirPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelSenhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                .addComponent(jPanelHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(858, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("EEEE', 'd 'de' MMMM 'de' yyyy");
        jLabeData.setText(formato.format(dataSistema));
        
        Timer timer = new Timer(1000, new hora());
        timer.start();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Integer opcao = JOptionPane.showConfirmDialog(this, "Deseja Realmente Sair?","Confirmação de Saída", JOptionPane.OK_CANCEL_OPTION);
        if (opcao!=2 && opcao!=-1){
            if (RegistroSenhas.size()==0){
                System.exit(0);
            }
            else{
                Object contador;
                contador = RegistroSenhas.get(RegistroSenhas.size() - 1);

                String arq = "senha.txt";
                String texto = contador.toString();

                if(Arquivo.Write(arq, texto))
                JOptionPane.showMessageDialog(this, "Arquivo salvo com sucesso");
                else
                JOptionPane.showConfirmDialog(this, "Erro ao salvar o arquivo");

                System.exit(0);
            }
        }
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaSenhaActionPerformed
        // TODO add your handling code here:

        if (numSenha==1){
            String arq = "senha.txt";
            String texto = Arquivo.Read(arq);
            if(texto.isEmpty())
            JOptionPane.showMessageDialog(this, "Erro ao ler do arquivo");
            else
            numSenha = Integer.parseInt(texto);
            //JOptionPane.showMessageDialog(this, texto);
            numSenha++;
        }
        else{
            DefaultTableModel tabela = (DefaultTableModel) jTableSenhas.getModel();
            Object[] senhas = {numSenha};
            tabela.addRow(senhas);
            regSenha = Integer.toString(numSenha);
            RegistroSenhas.add(regSenha);
            numSenha++;
        }
    }//GEN-LAST:event_jButtonNovaSenhaActionPerformed

    private void jButtonAbrirPainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPainelActionPerformed
        // TODO add your handling code here:
        TelaPainel novatela = new TelaPainel();
        novatela.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirPainelActionPerformed

    private void jButtonRechamarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechamarSenhaActionPerformed
        // TODO add your handling code here:
        jLabelSenhaAtual.setForeground(Color.red);
        TelaPainel.jLabelSenhaAtual.setForeground(Color.red);
    }//GEN-LAST:event_jButtonRechamarSenhaActionPerformed

    private void jButtonApagarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarSenhaActionPerformed
        // TODO add your handling code here:
        if (jTableSenhas.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "Selecione uma senha");
        }
        else if (JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir?","Confirmação de Exclusão",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
            ((DefaultTableModel)jTableSenhas.getModel()).removeRow(jTableSenhas.getSelectedRow());
        }
    }//GEN-LAST:event_jButtonApagarSenhaActionPerformed

    private void jButtonChamarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChamarSenhaActionPerformed
        // TODO add your handling code here:
        if (jTableSenhas.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "Selecione uma senha");
        }
        else{
            jLabelSenhaAtual.setForeground(Color.WHITE);
            jLabelSenhaAtual.setText(jTableSenhas.getValueAt(jTableSenhas.getSelectedRow(), 0).toString());
            TelaPainel.jLabelSenhaAtual.setForeground(Color.WHITE);
            TelaPainel.jLabelSenhaAtual.setText(jTableSenhas.getValueAt(jTableSenhas.getSelectedRow(), 0).toString());

            //Adicionando senha na no array
            SenhasChamadas.add(jTableSenhas.getValueAt(jTableSenhas.getSelectedRow(), 0).toString());

            //Removendo a senha chamada da jTable
            ((DefaultTableModel)jTableSenhas.getModel()).removeRow(jTableSenhas.getSelectedRow());

            if (SenhasChamadas.size()==2){
                jLabelSenhaAnt.setText(SenhasChamadas.get(0));
                TelaPainel.jLabelSenhaAnt.setText(SenhasChamadas.get(0));
                regSenha = SenhasChamadas.get(1);

            }
            else if (SenhasChamadas.size()==3){
                jLabelSenhaAnt.setText(SenhasChamadas.get(1));
                jLabelSenhaAnt2.setText(SenhasChamadas.get(0));
                TelaPainel.jLabelSenhaAnt.setText(SenhasChamadas.get(1));
                TelaPainel.jLabelSenhaAnt2.setText(SenhasChamadas.get(0));
                regSenha = SenhasChamadas.get(2);

            }
            else if (SenhasChamadas.size()==4){
                jLabelSenhaAnt.setText(SenhasChamadas.get(2));
                jLabelSenhaAnt2.setText(SenhasChamadas.get(1));
                jLabelSenhaAnt3.setText(SenhasChamadas.get(0));
                regSenha = SenhasChamadas.get(3);
                TelaPainel.jLabelSenhaAnt.setText(SenhasChamadas.get(2));
                TelaPainel.jLabelSenhaAnt2.setText(SenhasChamadas.get(1));
                TelaPainel.jLabelSenhaAnt3.setText(SenhasChamadas.get(0));
                SenhasChamadas.remove(0);

            }

        }
    }//GEN-LAST:event_jButtonChamarSenhaActionPerformed

    private void jButtonConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigActionPerformed
        // TODO add your handling code here:
        Login novaJanelaLogin = new Login();
        novaJanelaLogin.setVisible(true);
    }//GEN-LAST:event_jButtonConfigActionPerformed

    private void jButtonNovaSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNovaSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_F3){
            jButtonNovaSenha.doClick();
        }
    }//GEN-LAST:event_jButtonNovaSenhaKeyPressed

    private void jButtonChamarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonChamarSenhaKeyPressed
        // TODO add your handling code here:  
    }//GEN-LAST:event_jButtonChamarSenhaKeyPressed

    private void jButtonRechamarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonRechamarSenhaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRechamarSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirPainel;
    private javax.swing.JButton jButtonApagarSenha;
    private javax.swing.JButton jButtonChamarSenha;
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonNovaSenha;
    private javax.swing.JButton jButtonRechamarSenha;
    public static javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabeData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelChamarSenha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelNovaSenha;
    private javax.swing.JLabel jLabelRechamarSenha;
    public static javax.swing.JLabel jLabelSenhaAnt;
    public static javax.swing.JLabel jLabelSenhaAnt2;
    public static javax.swing.JLabel jLabelSenhaAnt3;
    public static javax.swing.JLabel jLabelSenhaAtual;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelHora;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSenhas;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableSenhas;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            Calendar now = Calendar.getInstance();
            jLabelHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

}
