/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/*import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.PopupMenu;
*/
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JPanel;



/**
 *
 * @author Wagner
 */
public class TelaPainel extends javax.swing.JFrame {
    
    

    /**
     * Creates new form TelaPainel
     */
    public TelaPainel() {
        initComponents();    
    }
    
    
    
    public void maximizarTela(){
        setExtendedState(TelaPainel.MAXIMIZED_BOTH);
    }
    public void fecharJanela(){
        this.dispose();
    }
    public void minimizarTela(){
        setExtendedState(TelaPainel.ICONIFIED);
    }
    public void restaurarTela(){
        setSize(1024, 768);
    }
    public void alteraTextoTelaRestaurada(){
        jLabelSenhaAtual.setFont(new Font("Arial", Font.BOLD, 300));
        jLabelSenhaAnt.setFont(new Font("Arial", Font.BOLD, 100));
        jLabelSenhaAnt2.setFont(new Font("Arial", Font.BOLD, 100));
        jLabelSenhaAnt3.setFont(new Font("Arial", Font.BOLD, 100));
        jLabelTituloHistorico.setFont(new Font("Segoe UI", Font.PLAIN, 60));
    }
    public void alteraTextoTelaCheia(){
        jLabelSenhaAtual.setFont(new Font("Arial", Font.BOLD, 400));
        jLabelSenhaAnt.setFont(new Font("Arial", Font.BOLD, 130));
        jLabelSenhaAnt2.setFont(new Font("Arial", Font.BOLD, 130));
        jLabelSenhaAnt3.setFont(new Font("Arial", Font.BOLD, 130));
        jLabelTituloHistorico.setFont(new Font("Segoe UI", Font.PLAIN, 72));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupOpcoes = new javax.swing.JPopupMenu();
        jMenuTelaCheia = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuResturar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuMinimizar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuSair = new javax.swing.JMenuItem();
        jPanelSenhas = new javax.swing.JPanel();
        jLabelSenhaAtual = new javax.swing.JLabel();
        jLabelSenhaAnt = new javax.swing.JLabel();
        jLabelSenhaAnt2 = new javax.swing.JLabel();
        jLabelSenhaAnt3 = new javax.swing.JLabel();
        jLabelTituloHistorico = new javax.swing.JLabel();

        jMenuTelaCheia.setText("Exibir em Tela cheia");
        jMenuTelaCheia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTelaCheiaActionPerformed(evt);
            }
        });
        jPopupOpcoes.add(jMenuTelaCheia);
        jPopupOpcoes.add(jSeparator1);

        jMenuResturar.setText("Restaurar Tela");
        jMenuResturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuResturarActionPerformed(evt);
            }
        });
        jPopupOpcoes.add(jMenuResturar);
        jPopupOpcoes.add(jSeparator3);

        jMenuMinimizar.setText("Minimizar Janela");
        jMenuMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMinimizarActionPerformed(evt);
            }
        });
        jPopupOpcoes.add(jMenuMinimizar);
        jPopupOpcoes.add(jSeparator2);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jPopupOpcoes.add(jMenuSair);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelSenhas.setBackground(new java.awt.Color(36, 45, 67));
        jPanelSenhas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha Atual", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 60), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelSenhas.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSenhas.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jPanelSenhas.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanelSenhas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSenhasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelSenhasMouseReleased(evt);
            }
        });

        jLabelSenhaAtual.setFont(new java.awt.Font("Arial", 1, 300)); // NOI18N
        jLabelSenhaAtual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSenhaAtual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelSenhaAnt.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jLabelSenhaAnt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaAnt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelSenhaAnt2.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jLabelSenhaAnt2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaAnt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelSenhaAnt3.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jLabelSenhaAnt3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenhaAnt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelTituloHistorico.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        jLabelTituloHistorico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloHistorico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloHistorico.setText("Senhas Chamadas");

        javax.swing.GroupLayout jPanelSenhasLayout = new javax.swing.GroupLayout(jPanelSenhas);
        jPanelSenhas.setLayout(jPanelSenhasLayout);
        jPanelSenhasLayout.setHorizontalGroup(
            jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSenhasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSenhasLayout.createSequentialGroup()
                        .addComponent(jLabelSenhaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelSenhasLayout.createSequentialGroup()
                        .addComponent(jLabelSenhaAnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabelSenhaAnt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelSenhaAnt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74))
                    .addComponent(jLabelTituloHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)))
        );
        jPanelSenhasLayout.setVerticalGroup(
            jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSenhasLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabelSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanelSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSenhaAnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenhaAnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenhaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSenhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSenhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void jPanelSenhasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSenhasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() > 1) { 
            maximizarTela();
            //telaCheia();
        }
        else{
            
        }
    }//GEN-LAST:event_jPanelSenhasMouseClicked

    private void jPanelSenhasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSenhasMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            jPopupOpcoes.show(this, evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_jPanelSenhasMouseReleased

    private void jMenuTelaCheiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTelaCheiaActionPerformed
        // TODO add your handling code here:
        maximizarTela();
        alteraTextoTelaCheia();
    }//GEN-LAST:event_jMenuTelaCheiaActionPerformed

    private void jMenuMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMinimizarActionPerformed
        // TODO add your handling code here:
        minimizarTela();
    }//GEN-LAST:event_jMenuMinimizarActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        fecharJanela();
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuResturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuResturarActionPerformed
        // TODO add your handling code here:
        restaurarTela();
        alteraTextoTelaRestaurada();
    }//GEN-LAST:event_jMenuResturarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPainel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabelSenhaAnt;
    public static javax.swing.JLabel jLabelSenhaAnt2;
    public static javax.swing.JLabel jLabelSenhaAnt3;
    public static javax.swing.JLabel jLabelSenhaAtual;
    private javax.swing.JLabel jLabelTituloHistorico;
    private javax.swing.JMenuItem jMenuMinimizar;
    private javax.swing.JMenuItem jMenuResturar;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuTelaCheia;
    private javax.swing.JPanel jPanelSenhas;
    private javax.swing.JPopupMenu jPopupOpcoes;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

    private void Principal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
